"""empty message

Revision ID: 467010385040
Revises: 7d6c9ec2d6a3
Create Date: 2023-05-22 10:15:21.368455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467010385040'
down_revision = '7d6c9ec2d6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
